### ISSUE TITLE
Offer possibility to revoke opt-in

### ISSUE THREAD

**Issue by cmb69** [cmb69/privacy_xh#8]
This is quite likely necessary for GDPR conformance. See also https://cmsimpleforum.com/viewtopic.php?f=16&t=13820&p=66870#p66870.

**Comment by cmb69** [comment]
How should we provide to display a form, so users can change their original decision to allow or to refuse cookies? Since the `#privacy` form is gone after users have chosen, should we provide an additional plugin call, say `privacy_status()`? How should this form look like?

How to deal with cookies already set by others (plugins etc.) after the user originally opted-in? Likely, we shouldn't touch them since we can't possibly know which ones are subject to privacy concerns. Should we include a link to some general instructions on how to remove cookies?

**Comment by pierrealexaline** [comment]
perheaps you can add a nber to cookies or in the cookies to indicate a level of privacy ....or something like this.

**Comment by cmb69** [comment]
See also https://cmsimpleforum.com/viewtopic.php?f=16&t=14664&p=79001#p79001.
